# Используем официальный образ Python
FROM python:3.11.8-slim AS build
# Устанавливаем рабочую директорию
WORKDIR /api
# Копируем файл с зависимостями в контейнер
COPY ./api/requirements.txt .
# Устанавливаем необходимые зависимости
RUN pip install -r requirements.txt
# Копируем файл с кодом в контейнер
COPY ./api/ .

FROM build AS final
WORKDIR /api
# Команда для запуска приложения
CMD ["python", "-u", "main.py"]